# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = migrations

# template used to generate migration files
# file_template = %%(rev)s_%%(slug)s

# sys.path path, space-separated, simple classic path format
# prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# timezone =

# max length of characters to allow for tag
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow array encoding to be passed to database
# encode_json = false

# set to 'true' to allow nulls to be returned from JSON columns
# json_nullable = false

# set to 'true' to use the newer, transactional DDL support
# (only works on postgresql)
# use_transactional_ddl = true

# logging configuration is at the end of the file

# sqlalchemy.url is set in env.py dynamically

[post_write_hooks]

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARNING
handlers = console
qualname =

[logger_sqlalchemy]
level = WARNING
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(asctime)s %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
